
export const artists = [
  "Steve Perry",
  "Paul McCartney",
  "Stevie Nicks",
  "Freddie Mercury",
  "Chris Cornell",
  "Axl Rose",
  "Roger Daltrey",
  "Bon Scott",
  "Bono",
  "Eddie Vedder",
  "Steven Tyler",
  "John Lennon",
  "Ann Wilson",
  "Debbie Harry",
  "David Bowie",
  "Bob Dylan",
  "Elvis Presley",
  "Joe Strummer",
  "Jerry Garcia",
  "Kurt Cobain",
  "Rob Halford",
  "Brittany Howard",
  "Jack White",
  "Roy Orbison",
  "Thom Yorke",
  "Janis Joplin",
  "Tom Petty",
  "George Clinton",
  "Chester Bennington",
  "David Lee Roth",
  "John Fogerty",
  "Little Richard",
  "Rod Stewart",
  "Dave Grohl",
  "Brian Wilson",
  "Grace Slick",
  "Robert Smith",
  "Michael Stipe",
  "Iggy Pop",
  "Ronnie James Dio",
  "Pat Benatar",
  "David Byrne",
  "Van Morrison",
  "Liam Gallagher",
  "Elvis Costello",
  "Phil Collins",
  "George Harrison",
  "Peter Gabriel",
  "Tupac Shakur",
  "Jay-Z",
  "Eminem",
  "Diego el Cigala",
  "Elton John",
  "David Bowie",
  "Bob Dylan",
  "Van Morrison",
  "John Lennon",
  "Alice Cooper",
  "Jim Morrison",
  "Steven Tyler",
  "Jimi Hendrix",
  "Carlos Santana",
  "Frank Zappa",
  "Barry White",
  "Diana Ross",
  "Michael Jackson",
  "Neil Young",
  "Stevie Wonder",
  "Bruce Springsteen",
  "Marvin Gaye",
  "Al Green",
  "Eric Clapton",
  "James Brown",
  "Iggy Pop",
  "Lou Reed",
  "Bob Marley",
  "Patti Smith",
  "Peter Frampton",
  "Donna Summer",
  "Freddie Mercury",
  "George Harrison",
  "Joe Cocker",
  "Paul Simon",
  "Kurt Cobain",
  "Ray Charles",
  "Aretha Franklin",
  "Ben E. King",
  "Al Green",
  "Marvin Gaye",
  "Jimi Hendrix",
  "Stevie Wonder",
  "James Brown",
  "Gladys Knight",
  "Donna Summer",
  "Roberta Flack",
  "George Duke",
  "Michael Jackson",
  "Diana Ross",
  "Barry White",
  "Ike Turner",
  "Ray Charles",
  "James Brown",
  "Aretha Franklin",
  "Fela Aníkúlápó Kuti",
  "Iggy Pop",
  "Paul McCartney",
  "Rihanna",
  "Madonna",
  "Jay-Z",
  "Celine Dion",
  "Dolly Parton",
  "Bono",
  "Diddy",
  "Julio Iglesias",
  "Barbra Streisand",
  "Bruce Springsteen",
  "Dr. Dre",
  "Jon Bon Jovi",
  "Calvin Harris",
  "Ringo Starr",
  "John Lennon",
  "Paul McCartney",
  "Robert Plant",
  "Elton John",
  "Celine Dion",
  "Billy Joel",
  "Justin Bieber",
  "Bruno Mars",
  "Britney Spears",
  "Bruce Springsteen",
  "Bono",
  "James Hetfield",
  "Steven Tyler",
  "Phil Collins",
  "Barbra Streisand",
  "Agnetha Fältskog",
  "Julio Iglesias",
  "Frank Sinatra",
  "Katy Perry",
  "Chris Brown",
  "Jay-Z",
  "Lady Gaga",
  "Adam Levine",
  "Adele",
  "Anthony Kiedis",
  "Jon Bon Jovi",
  "Rod Stewart",
  "Nicki Minaj",
  "Chris Martin",
  "George Strait",
  "Shania Twain",
  "Eric Clapton",
  "Neil Diamond",
  "Prince",
  "Paul McCartney",
  "Janet Jackson",
  "Kenny Rogers",
  "Art Garfunkel",
  "Paul Simon",
  "Jim Morrison",
  "George Michael",
  "Mark Knopfler",
  "Lou Gramm",
  "Bob Dylan",
  "Meat Loaf",
  "Karen Carpenter",
  "Cher",
  "David Bowie",
  "Whitney Houston",
  "Bob Dylan",
  "Karen Carpenter",
  "Cher",
  "David Bowie",
  "Eminem",
  "George Strait",
  "Enya",
  "Kurt Cobain",
  "Anthony Kiedis",
  "Britney Spears",
  "Mick Jagger",
  "Jim Morrison",
  "George Michael",
  "Mark Knopfler",
  "Lou Gramm",
  "Bob Marley",
  "Jon Bon Jovi",
  "Eminem",
  "David Bowie",
  "Axl Rose",
  "George Michael",
  "Enya",
  "Kurt Cobain",
  "Anthony Kiedis",
  "Britney Spears",
  "Mick Jagger",
  "Aretha Franklin",
  "Frank Sinatra",
  "Bob Dylan",
  "Prince",
  "David Bowie",
  "Stevie Wonder",
  "Ray Charles",
  "Tina Turner",
  "Celine Dion",
  "Elton John",
  "Janis Joplin",
  "Bruce Springsteen",
  "Kurt Cobain",
  "Jim Morrison",
  "Billie Holiday",
  "Nina Simone",
  "Barbra Streisand",
  "James Brown",
  "Johnny Cash",
  "Etta James",
  "Dolly Parton",
  "Marvin Gaye",
  "George Michael",
  "Björk",
  "Amy Winehouse",
  "Christina Aguilera",
  "Justin Timberlake",
  "Billy Joel",
  "Cher",
  "Paul Simon",
  "Patti Smith",
  "Diana Ross",
  "Axl Rose",
  "Jon Bon Jovi",
  "Thom Yorke",
  "Bono",
  "Mick Jagger",
  "Lou Reed",
  "Rod Stewart",
  "Phil Collins",
  "Sam Cooke",
  "Sade",
  "George Harrison",
  "Karen Carpenter",
  "Brian Wilson",
  "Linda Ronstadt",
  "Robert Plant",
  "Jeff Buckley",
  "Alicia Keys",
  "Shakira",
  "Christina Perri",
  "Ed Sheeran",
  "Drake",
  "Eminem",
  "Kanye West",
  "Taylor Swift",
  "Nicki Minaj",
  "Lady Gaga",
  "Billie Eilish",
  "Harry Styles",
  "Olivia Rodrigo",
  "Usher",
  "Brandy",
  "Lauryn Hill",
  "Lionel Richie",
  "Nat King Cole",
  "Dean Martin",
  "Barry White",
  "Andrea Bocelli",
  "Luciano Pavarotti",
  "Enrico Caruso",
  "Enya",
  "Garth Brooks",
  "Shania Twain",
  "Chris Cornell",
  "Chester Benningt",
  "Steven Tyler",
  "Anthony Kiedis",
  "Ozzy Osbourne",
  "Layne Staley",
  "Dolores O'Riorda",
  "Rob Halford",
  "Thom Yorke",
  "Gwen Stefani",
  "Alanis Morissett",
  "Tori Amos",
  "Florence Welch",
  "Annie Lennox",
  "Joan Baez",
  "Michael Bublé",
  "Aretha Franklin",
  "Marvin Gaye",
  "Sam Cooke",
  "Otis Redding",
  "James Brown",
  "Stevie Wonder",
  "Ray Charles",
  "Al Green",
  "Smokey Robinson",
  "Curtis Mayfield",
  "Etta James",
  "Gladys Knight",
  "Donny Hathaway",
  "Bill Withers",
  "Luther Vandross",
  "Isaac Hayes",
  "Bobby Womack",
  "Tina Turner",
  "Patti LaBelle",
  "Mavis Staples",
  "Wilson Pickett",
  "Solomon Burke",
  "Jackie Wilson",
  "Percy Sledge",
  "D’Angelo",
  "Sade",
  "Lauryn Hill",
  "Alicia Keys",
  "Mary J. Blige",
  "Anthony Hamilton",
  "Maxwell",
  "Erykah Badu",
  "Angie Stone",
  "Raphael Saadiq",
  "Joss Stone",
  "Amy Winehouse",
  "Leon Bridges",
  "John Legend",
  "Charles Bradley",
  "Betty Wright",
  "Sharon Jones",
  "Gregory Porter",
  "Jennifer Hudson",
  "Fantasia Barrino",
  "Lalah Hathaway",
  "Chrisette Michel",
  "Teena Marie",
  "Chaka Khan",
  "Minnie Riperton",
  "Bettye LaVette",
  "Ann Peebles",
  "Jean Knight",
  "Marlena Shaw",
  "Peabo Bryson",
  "Bobby Bland",
  "Alicia Myers",
  "Melba Moore",
  "Toni Braxton",
  "Seal",
  "Terence Trent D’",
  "Donell Jones",
  "Musiq Soulchild",
  "Angie Fisher",
  "Tank",
  "Van Hunt",
  "Leela James",
  "Bilal",
  "PJ Morton",
  "Michael Kiwanuka",
  "Sam Smith",
  "Ella Mai",
  "Daniel Caesar",
  "Jazmine Sullivan",
  "Arlo Parks",
  "Otis Clay",
  "Major Harris",
  "Clarence Carter",
  "Freddie Jackson",
  "Howard Hewett",
  "Sy Smith",
  "Meshell Ndegeoce",
  "Marlena Shaw",
  "Oleta Adams",
  "Curtis Harding",
  "James Carr",
  "Leroy Hutson",
  "Sampha",
  "Michael McDonald",
  "Boz Scaggs (soul",
  "Jessie Ware",
  "Teddy Pendergras",
  "B.B. King",
  "Muddy Waters",
  "Robert Johnson",
  "Howlin’ Wolf",
  "John Lee Hooker",
  "Etta James",
  "Willie Dixon",
  "Rory Gallagher",
  "Bo Diddley",
  "Ma Rainey",
  "Bessie Smith",
  "Memphis Minnie",
  "Taj Mahal",
  "Eric Clapton",
  "Stevie Ray Vaugh",
  "Jimi Hendrix",
  "Otis Taylor",
  "Corey Harris",
  "Robert Cray",
  "Ana Popović",
  "Guy-Manuel de Homem-Ch",
  "Thomas Bangalter",
  "Kraftwerk",
  "Brian Eno",
  "Aphex Twin",
  "Richard D. James",
  "Daft Punk",
  "The Chemical Brothers",
  "Tom Rowlands",
  "Ed Simons",
  "Fatboy Slim",
  "Norman Cook",
  "Deadmau5",
  "Joel Zimmerman",
  "Skrillex",
  "Sonny Moore",
  "Armin van Buuren",
  "Tiesto",
  "Calvin Harris",
  "Diplo",
  "Moby",
  "Paul Oakenfold",
  "Paul van Dyk",
  "Carl Cox",
  "Richie Hawtin",
  "Eric Prydz",
  "Steve Aoki",
  "Zedd",
  "Martin Garrix",
  "Kygo",
  "Marshmello",
  "Porter Robinson",
  "Madeon",
  "Benny Benassi",
  "Justice",
  "Boys Noize",
  "Flume",
  "Alesso",
  "Hardwell",
  "Afrojack",
  "Axwell",
  "Sebastian Ingrosso",
  "Steve Angello",
  "deadmau5",
  "Duke Dumont",
  "Disclosure",
  "Jamie xx",
  "Bonobo",
  "Jon Hopkins",
  "James Blake",
  "Nina Kraviz",
  "Peggy Gou",
  "Charlotte de Witte",
  "Amelie Lens",
  "Rezz",
  "Alison Wonderland",
  "RL Grime",
  "Baauer",
  "Hudson Mohawke",
  "Machinedrum",
  "Kaytranada",
  "Arca",
  "SOPHIE",
  "Burial",
  "Jamie Jones",
  "Nicolas Jaar",
  "DJ Snake",
  "Jai Paul",
  "Claptone",
  "Bicep",
  "Todd Terje",
  "Mr. Oizo",
  "Luciano",
  "Moderat",
  "Skream",
  "Benga",
  "Andy C",
  "Shygirl",
  "Octo Octa",
  "Sasha",
  "John Digweed",
  "Adam Beyer",
  "Len Faki",
  "DJ Koze",
  "The Blessed Madonna",
  "Tokimonsta",
  "SOFI TUKKER",
  "The Glitch Mob",
  "Chrome Sparks",
  "Paul Kalkbrenner",
  "DJ Shadow",
  "Trentemøller",
  "Ali Farka Touré",
  "Manu Chao",
  "Fela Kuti",
  "Cesaria Evora",
  "Bob Marley",
  "Jeff Buckley",
  "Ben Harper",
  "Daft Punk",
  "Camaron De La Isla",
  "Paco De Lucia",
  "Phil Colins",
  "Sting",
  "Supertramp",
  "Saian Supa Crew",
  "Charles Aznavour",
  "Jacque Brel",
  "Yves Montand",
  "Fat Freddy's Drop",
  "Erykah Badu",
  "Curtis Mayfield",
  "Lauryn Hill",
  "Carlos Santana",
  "Marvin Gaye",
  "Aaron Taylor",
  "Keziah Jones",
  "Masego",
  "Duke Ellington",
  "Portishead",
  "Prince",
  "Ray Charles",
  "FKJ",
  "Fleetwood Mac",
  "Amy Winehouse",
  "Maceo Parker",
  "Manu Dibango",
  "John Coltrane",
  "The Clash",
  "Sex Pistols",
  "The Doors",
  "Jefferson Airplane",
  "Led Zeppelin",
  "Buena Vista Social Club",
  "Iseo & Dodosound",
  "Gotan Project",
  "Ojos De Brujo",
  "Bomba Estereo",
  "NTM",
  "Morcheeba",
  "Edwin Starr",
  "Kool and The Gang",
  "Rick James",
  "The Jackson 5",
  "Fugees",
  "Youssou N' Dour",
  "Salif Keita"
]